const componentsLightTheme = {
  klerosUIComponentsName: "light",
  klerosUIComponentsPrimaryPurple: "#4D00B4",
  klerosUIComponentsSecondaryPurple: "#9013FE",
  klerosUIComponentsMediumPurple: "#F8F1FF",
  klerosUIComponentsLightPurple: "#FBF9FE",
  klerosUIComponentsPrimaryBlue: "#009AFF",
  klerosUIComponentsSecondaryBlue: "#7BCBFF",
  klerosUIComponentsMediumBlue: "#F0F9FF",
  klerosUIComponentsLightBlue: "#FCFEFF",
  klerosUIComponentsPrimaryText: "#333333",
  klerosUIComponentsSecondaryText: "#999999",
  klerosUIComponentsStroke: "#e5e5e5",
  klerosUIComponentsLightGrey: "#FAFAFA",

  klerosUIComponentsWhiteBackground: "#FFFFFF",
  klerosUIComponentsLightBackground: "#FAFBFC",

  klerosUIComponentsDefaultShadow: "#00000002",
  klerosUIComponentsHoveredShadow: "#00000002",

  klerosUIComponentsSuccess: "#00C42B",
  klerosUIComponentsSuccessLight: "#F0FBF2",
  klerosUIComponentsWarning: "#FF9900",
  klerosUIComponentsWarningLight: "#FFF9F0",
  klerosUIComponentsError: "#F60C36",
  klerosUIComponentsErrorLight: "#FEFF0F3",
  klerosUIComponentsTint: "#D14EFF",
  klerosUIComponentsTintMedium: "#401D6C",
  klerosUIComponentsTintPurple: "#F4F0FA",

  klerosUIComponentsTransitionSpeed: "0.25s",
};

const componentsDarkTheme = {
  klerosUIComponentsName: "dark",
  klerosUIComponentsPrimaryPurple: "#7E1BD4",
  klerosUIComponentsSecondaryPurple: "#B45FFF",
  klerosUIComponentsMediumPurple: "#390F6C",
  klerosUIComponentsLightPurple: "#FCFBFF",
  klerosUIComponentsPrimaryBlue: "#6CC5FF",
  klerosUIComponentsSecondaryBlue: "#A5DBFF",
  klerosUIComponentsMediumBlue: "#2E206C",
  klerosUIComponentsLightBlue: "#2A1260",
  klerosUIComponentsPrimaryText: "#DAF0FF",
  klerosUIComponentsSecondaryText: "#BECCE5",
  klerosUIComponentsStroke: "#392C74",
  klerosUIComponentsLightGrey: "#2D1865",

  klerosUIComponentsWhiteBackground: "#220050",
  klerosUIComponentsLightBackground: "#1B003F",

  klerosUIComponentsDefaultShadow: "#00000000",
  klerosUIComponentsHoveredShadow: "#42498f80",

  klerosUIComponentsSuccess: "#65DC7F",
  klerosUIComponentsSuccessLight: "#32355B",
  klerosUIComponentsWarning: "#FFC46B",
  klerosUIComponentsWarningLight: "#451F54",
  klerosUIComponentsError: "#FF5A78",
  klerosUIComponentsErrorLight: "#360652",
  klerosUIComponentsTint: "#DDB6FF",
  klerosUIComponentsTintMedium: "#401D6C",
  klerosUIComponentsTintPurple: "#2F0960",

  klerosUIComponentsTransitionSpeed: "0.25s",
};
export const lightTheme = {
  ...componentsLightTheme,
  name: "light",
  white: "#FFFFFF",
  black: "#000000",
  primaryPurple: "#4D00B4",
  secondaryPurple: "#9013FE",
  darkPurple: "#220050",
  mediumPurple: "#F8F1FF",
  lightPurple: "#FBF9FE",
  violetPurple: "#6A1DCD",
  lavenderPurple: "#BB72FF",
  primaryBlue: "#009AFF",
  secondaryBlue: "#7BCBFF",
  mediumBlue: "#F0F9FF",
  lightBlue: "#FCFEFF",
  primaryText: "#333333",
  secondaryText: "#999999",
  stroke: "#e5e5e5",
  lightGrey: "#F0F0F0",

  whiteBackground: "#FFFFFF",
  lightBackground: "#FAFBFC",

  defaultShadow: "#00000002",
  hoveredShadow: "#00000002",
  whiteLowOpacitySubtle: "#FFFFFF0D",
  whiteLowOpacityStrong: "#FFFFFF26",
  blackLowOpacity: "#00000080",

  success: "#00C42B",
  successLight: "#F0FBF2",
  warning: "#FF9900",
  warningLight: "#FFF9F0",
  error: "#F60C36",
  errorLight: "#FEF0F3",
  tint: "#D14EFF",
  tintMedium: "#FCF4FF",
  tintPurple: "#F4F0FA",

  transitionSpeed: "0.25s",

  skeletonBackground: "#EBEBEB",
  skeletonHighlight: "#F5F5F5",

  paleCyan: "#ACFFFF",
  limeGreen: "#F3FFD9",
};

export const darkTheme = {
  ...componentsDarkTheme,
  name: "dark",
  white: "#FFFFFF",
  black: "#000000",
  primaryPurple: "#7E1BD4",
  secondaryPurple: "#B45FFF",
  darkPurple: "#220050",
  mediumPurple: "#390F6C",
  lightPurple: "#FCFBFF",
  violetPurple: "#6A1DCD",
  lavenderPurple: "#BB72FF",
  primaryBlue: "#6CC5FF",
  secondaryBlue: "#A5DBFF",
  mediumBlue: "#2E206C",
  lightBlue: "#2A1260",
  primaryText: "#DAF0FF",
  secondaryText: "#BECCE5",
  stroke: "#392C74",
  lightGrey: "#2D1865",

  whiteBackground: "#220050",
  lightBackground: "#1B003F",

  defaultShadow: "#00000000",
  hoveredShadow: "#42498f80",
  whiteLowOpacitySubtle: "#FFFFFF0F",
  whiteLowOpacityStrong: "#FFFFFF24",
  blackLowOpacity: "#00000080",

  success: "#65DC7F",
  successLight: "#32355B",
  warning: "#FFC46B",
  warningLight: "#451F54",
  error: "#FF5A78",
  errorLight: "#360652",
  tint: "#DDB6FF",
  tintMedium: "#401D6C",
  tintPurple: "#2F0960",

  transitionSpeed: "0.25s",

  skeletonBackground: "#3A2270",
  skeletonHighlight: "#3E307C",

  paleCyan: "#ACFFFF",
  limeGreen: "#F3FFD9",
};
